#!/bin/bash
eval $(jq -r '. as $p | 
  "name=\($p.name | ascii_upcase)
   type=\($p.types[0].type.name | ascii_upcase)
   formatted_weight=\($p.weight / 10)
   formatted_height=\($p.height / 10)"' data.json)
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
