#!/bin/bash

jq -r '
  .name + " " + 
  (.types[0].type.name | ascii_upcase[:1] + .[1:]) + " " + 
  (.weight/10 | tostring) + " " + 
  (.height/10 | tostring)
' data.json |
awk '{
  # Format weight and height (remove trailing .0 if present)
  sub(/\.0$/, "", $3);
  sub(/\.0$/, "", $4);
  
  # Capitalize first letter of name (already handled for type in jq)
  first_char = substr($1, 1, 1);
  $1 = toupper(first_char) substr($1, 2);
  
  print $1 " is of type " $2 ", weighs " $3 "kg, and is " $4 "m tall."
}' |
sed '
  s/weighs kg/weighs 0kg/;
  s/is m tall/is 0m tall/
'