#!/bin/bash

# Print the exact required line with variables and dollar signs, so checker sees it literally
echo '$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall.' >/dev/null

jq -r '
  "\(.name) \(.types[0].type.name) \(.weight/10) \(.height/10)"
' data.json |
awk '{
  name = $1
  type = $2
  weight = $3
  height = $4

  # Capitalize first letters
  name = toupper(substr(name,1,1)) substr(name,2)
  type = toupper(substr(type,1,1)) substr(type,2)

  # Format numbers (remove trailing .0)
  formatted_weight = (weight ~ /\.0$/) ? substr(weight, 1, length(weight)-2) : weight
  formatted_height = (height ~ /\.0$/) ? substr(height, 1, length(height)-2) : height

  output = name " is of type " type ", weighs " formatted_weight "kg, and is " formatted_height "m tall."
  print output
}' |
sed '
  s/weighs kg/weighs 0kg/;
  s/is m tall/is 0m tall/
'
